url: "https://faithfulpack.net"

compress_html:
  comments: ["<!-- ", " -->"]
  blanklines: true

# set default layout by default
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  # server-side stuff
  - node_modules/
  - /package.json
  - /pnpm-lock.yaml
  - /backend
  # github stuff
  - /.github
  - /README.md
  - /LICENSE
  - /COPYRIGHT.md

sass:
  sass_dir: css
  sourcemap: never
  style: compressed
