name: Deploy Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH }}
        # install bundle, build jekyll, relaunch website
        script: |
          cd /var/www/html/faithfulpack.net
          git stash
          git pull
          pnpm install
          pnpm run ji
          pnpm run jb
          pnpm run optimize
          pm2 restart "WEBSITE"
    - name: Purge Cloudflare cache
      run: "curl https://api.faithfulpack.net/v2/cloudflare/purge -H 'cloudflare: ${{ secrets.PURGE_PASSWORD }}'"
