name: Deploy Website

on:
  push:
    branches: [ nuxt-rewrite ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH }}
        # reload dependencies, build nuxt files, start server
        script: |
          cd /var/www/html/beta.faithfulpack.net
          git stash
          git pull
          pnpm install
          pnpm run build
          pm2 restart website-nuxt
    - name: Purge Cloudflare cache
      run: "curl https://api.faithfulpack.net/v2/cloudflare/purge -H 'cloudflare: ${{ secrets.PURGE_PASSWORD }}'"
